GET http://localhost:3050/bank-accounts

###
GET http://localhost:3050/bank-accounts/123

###
POST http://localhost:3050/bank-accounts
Content-Type: application/json

{
  "account_number": 123
}

###
PATCH http://localhost:3050/bank-accounts/123
Content-Type: application/json

{
  "account_number": 123
}

###
DELETE http://localhost:3050/bank-accounts/123
