GET http://localhost:3050/bank-accounts

###
GET http://localhost:3050/bank-accounts/e9b660b9-f79b-4446-b487-91275ec9a714

###
POST http://localhost:3050/bank-accounts
Content-Type: application/json

{
  "account_number": "2222-22"
}

###
PATCH http://localhost:3050/bank-accounts/123
Content-Type: application/json

{
  "account_number": "1111-11"
}

###
DELETE http://localhost:3050/bank-accounts/4f4bb3bb-df05-46f2-a4b5-31f4022bb75f

###
POST http://localhost:3050/bank-accounts/transfer
Content-Type: application/json

{
  "from": "1111-11",
  "to": "2222-22",
  "amount": 100
}